FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install dotenv
RUN npm install pg
RUN npm install bcrypt
RUN npm install jsonwebtoken

COPY . .

EXPOSE 3001

ENV NODE_ENV=development

CMD ["node", "index.js"]