FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install passport
RUN npm install passport-github2
RUN npm install express-session

COPY . .

EXPOSE 3001

ENV NODE_ENV=development

CMD ["node", "index.js"]
